RoomManagement/Areas/Admin/Controllers/PriceManagementController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Mapster;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RoomManagement.Areas.Admin.Models.PriceManagementModel;
using RoomManagement.Areas.Admin.Models.RoomModel;
using RoomManagement.Areas.Admin.Models.VoucherModel;
using RoomManagement.Core.Collections;
using RoomManagement.Core.DTO;
using RoomManagement.Core.Entites;
using RoomManagement.Models;
using RoomManagement.Services.Media;
using RoomManagement.Services.RoomMangementService.PriceManagementSerivce;
using RoomManagement.Services.RoomMangementService.RoomSerivce;
using RoomManagement.Services.RoomMangementService.RoomTypeSerivce;
using RoomManagement.Services.RoomMangementService.VoucherSerivce;

namespace RoomManagement.Areas.Admin.Controllers
{
    public class PriceManagementController : Controller
    {
        private readonly IRoomTypeRepository _roomTypeRepository;
        private readonly IRoomRepository _roomRepository;
        private readonly IVoucherRepository _voucherRepository;
        private readonly IPriceManagementRepository _priceManagementRepository;
        private readonly IMediaManager _mediaManager;
        private readonly IMapper _mapper;
        private readonly IValidator<RoomEditModel> _validator;
        public PriceManagementController(IRoomTypeRepository roomTypeRepository,
            IRoomRepository roomRepository,
            IVoucherRepository voucherRepository,
            IPriceManagementRepository priceManagementRepository,
            IMediaManager mediaManager,
            IMapper mapper,
            IValidator<RoomEditModel> validator
            )
        {
            _roomTypeRepository = roomTypeRepository;
            _roomRepository = roomRepository;
            _voucherRepository = voucherRepository;
            _priceManagementRepository = priceManagementRepository;
            _mediaManager = mediaManager;
            _mapper = mapper;
            _validator = validator;

        }

        public async Task<IActionResult> Index(

            PriceManagementFilterModel model,
            [FromQuery(Name = "p")] int pageNumber = 1,
            [FromQuery(Name = "ps")] int pageSize = 10
            )
        {
            var priceManagementQuery = _mapper.Map<PriceManagementQuery>(model);
            var priceManagementList = await _priceManagementRepository.GetPriceManagementsByQuery(priceManagementQuery, new PagingModel() { PageSize = pageSize, PageNumber = pageNumber }, priceManagements => priceManagements.ProjectToType<PriceManagementDto>());

            ViewBag.PageType = "Giá phòng";

            ViewBag.PriceManagementList = new PaginationResult<PriceManagementDto>(priceManagementList);
            ViewData["Query"] = model;
            return View("Index", model);

        }


        [HttpPost]
        public async Task<IActionResult> Edit([FromServices]
             IValidator<PriceManagementEditModel> voucherValidator, PriceManagementEditModel model)
        {

            //slug null
            var validationResult = await voucherValidator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(ModelState);
            }
            if (!ModelState.IsValid)
            {
                //await PopulatePostsEditModelAsync(model);
                return View(model);
            }

            var priceManament = model.Id > 0
              ? await _priceManagementRepository.GetPriceManagementByIdAsync(model.Id)
              : null;

            if (priceManament == null)
            {
                priceManament = _mapper.Map<PriceManagement>(model);
                priceManament.Id = 0;

            }
            else
            {
                _mapper.Map(model, priceManament);

            }




            await _priceManagementRepository.AddOrUpdatePriceManagement(priceManament);


            return RedirectToAction(nameof(Index));

        }



        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var priceManagement = id > 0
           ? await _priceManagementRepository.GetPriceManagementByIdAsync(id)
           : null;

            var model = priceManagement == null
            ? new PriceManagementEditModel()
            : _mapper.Map<PriceManagementEditModel>(priceManagement);

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> DeletePriceManagement(int id)
        {
            var PriceManagementQuey = await _priceManagementRepository.DeletePriceManagement(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> VerifyPriceManagementSlug(int id, string urlSlug)
        {
            var slugExisted = await _priceManagementRepository.IsPriceManagementSlugExistedAsync(id, urlSlug);
            return slugExisted ? Json($"slug '{urlSlug}'  đã được sử dụng") : Json(true);
        }

        public async Task PopulatePriceManagementsFitlterModelAsync(PriceManagementFilterModel model)
        {
            var priceManagements = await _priceManagementRepository.GetAllAsync();
            model.PriceManagementList = priceManagements.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = c.Id.ToString(),
            });
        }
    }
}

RoomManagement/Areas/Admin/Views/PriceManagement/Edit.cshtml
@using RoomManagement.Areas.Admin.Models.PriceManagementModel;
@model PriceManagementEditModel;

@{
    ViewData["Title"] = "Thêm/ Cập nhập Giá";
}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <h4>Thêm/ Cập nhập Giá</h4>
        <form method="post"
              enctype="multipart/form-data"
              asp-area="Admin"
              asp-controller="PriceManagement"
              asp-action="Edit">
            <div asp-validation-summary="ModelOnly"></div>
            <input type="hidden" asp-for="Id">
            @* tên phòng  *@
            <div class="form-group">
                <label asp-for="Name" class="col-sm-5 col-form-label"></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Name">
                    <span class="text-danger"
                          asp-validation-for="Name"></span>
                </div>
            </div>

            @* Slug*@

            <div class="form-group">
                <label asp-for="UrlSlug" class="col-sm-5 col-form-label"></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="UrlSlug">
                    <span class="text-danger"
                          asp-validation-for="UrlSlug"></span>
                </div>
            </div>
            @* mô tả về phòng  *@

            <div class="form-group">
                <label asp-for="Description" class="col-sm-5 col-form-label"></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Description">
                    <span class="text-danger"
                          asp-validation-for="Description"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="col-sm-5 col-form-label"></label>
                <div class="col-sm-10">
                    <input type="number" class="form-control" asp-for="Price">
                    <span class="text-danger"
                          asp-validation-for="Price"></span>
                </div>
            </div>

            <div class="text-center">
                <button type="submit" class="btn btn-primary">
                    Lưu các thay đổi
                </button>
                <a class="btn btn-danger"
                   asp-area="Admin"
                   asp-controller="PriceManagement"
                   asp-action="Index">
                    Hủy & Quay lại
                </a>
            </div>
        </form>
    </div>
</div>
</div>

@section scripts
    {
    <partial name="_ValidationScriptsPartial" />

    <script src="~/lib/speakingurl/speakingurl.min.js"></script>

    <script>
        $(function () {
            $('#Name').change(function () {
                var slug = getSlug(this.value);
                console.log(slug);
                $('#UrlSlug').val(slug).trigger('blur');
            });
        });
    </script>
}

RoomManagement/Areas/Admin/Views/PriceManagement/Index.cshtml
@using RoomManagement.Areas.Admin.Models.PriceManagementModel;

@model PriceManagementFilterModel;

@{
    CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");   // try with "en-US"

}
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <partial name="_Navbar" />
        <!-- end Topbar -->

        <div class="container-fluid">

            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800 text-center">Quản lý giá phòng</h1>
            <partial name="_FilterPanelPriceManagement" model="@Model" />
            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Thông tin giá cả</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Tên</th>
                                    <th>Mô tả</th>
                                    <th>Giá</th>
                                    <th>UrlSlug</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.PriceManagementList.Items)
                                {
                                    <tr>
                                        <td>@item.Name</td>

                                        <td>@item.Description</td>
                                        <td>@string.Format("{0:#,##0.00} VNĐ", item.Price)</td>
                                        <td>@item.UrlSlug</td>

                                        <td>
                                            <div class="d-flex">
                                                <a asp-area="Admin" asp-controller="PriceManagement" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info btn-circle mx-2">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <button type="button" value="@item.Id" id="btn-item" class="btn btn-danger btn-circle mx-2" data-toggle="modal" data-target="#exampleModal">
                                                    <i class="fas fa-trash">

                                                    </i>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <partial name="_Pagination" model="@ViewBag.PriceManagementList.Metadata" />
            </div>

        </div>

    </div>


</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Xác nhận xóa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Bạn thực sự muốn xóa?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy bỏ</button>
                <button type="button" id="delete-id" class="btn btn-primary">Đồng ý</button>
            </div>
        </div>
    </div>
</div>
<form enctype="multipart/form-data"
      name="form-delete"
      asp-action="DeletePriceManagement"
      asp-controller="PriceManagement"
      asp-area="Admin">
</form>
@section Scripts{
    <script>

        var deleteForm = document.forms['form-delete'];
        var btnDelete = document.getElementById('btn-item');


        $("#delete-id").click(function () {
            deleteForm.action += "/" + btnDelete.value;
            deleteForm.submit();
        });
        $('#myModal').on('shown.bs.modal', function () {


            $('#myInput').trigger('focus')


        })
    </script>


 }

RoomManagement/Areas/Admin/Views/PriceManagement/_FilterPanelPriceManagement.cshtml
@using RoomManagement.Areas.Admin.Models.PriceManagementModel;
@model PriceManagementFilterModel;

<form asp-area="Admin"
      asp-controller="PriceManagement"
      asp-action="Index"
      method="get"
      class="row gy-2 gx-3 align-items-center mt-4 mb-4">

    <div class="col-auto">

        <input type="text"
               class="form-control"
               asp-for="Name"
               placeholder="Nhập từ khoá..." />
    </div>


    <div class="col-auto">
        <button type="submit" class="btn btn-primary">
            Tìm/Lọc
        </button>

        <a asp-area="Admin"
           asp-controller="PriceManagement"
           asp-action="Edit"
           class="btn btn-success">
            Thêm mới
        </a>
    </div>
    <div class="col-auto">
        <a asp-area="Admin"
           asp-controller="PriceManagement"
           asp-action="Index"
           class="btn btn-success">
            Bỏ Lọc
        </a>
    </div>
</form>