RoomManagement/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using RoomManagement.Services.RoomMangementService.DashboardService;

namespace RoomManagement.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepository _dashboardRepository;

        public DashboardController(IDashboardRepository dashboardRepository)
        {
            _dashboardRepository = dashboardRepository;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["TotalRoomTypes"] = await _dashboardRepository.GetTotalRoomTypesAsync();
            ViewData["TotalRooms"] = await _dashboardRepository.GetTotalRoomsAsync();
            ViewData["TotalVoucher"] = await _dashboardRepository.GetTotalVoucherAsync();
            ViewData["TotalPriceType"] = await _dashboardRepository.GetTotalPriceTypeAsync();

            ViewData["Analysis"] = await _dashboardRepository.GetRoomStatusInfo();
            return View();  
        }
    }
}

RoomManagement/Areas/Admin/Controllers/RoomController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Mapster;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using RoomManagement.Areas.Admin.Models.RoomModel;
using RoomManagement.Core.Collections;
using RoomManagement.Core.DTO;
using RoomManagement.Core.Entites;
using RoomManagement.Models;
using RoomManagement.Services.Media;
using RoomManagement.Services.RoomMangementService.PriceManagementSerivce;
using RoomManagement.Services.RoomMangementService.RoomSerivce;
using RoomManagement.Services.RoomMangementService.RoomTypeSerivce;
using RoomManagement.Services.RoomMangementService.VoucherSerivce;

namespace RoomManagement.Areas.Admin.Controllers
{
    public class RoomController : Controller
    {
        
        private readonly IRoomTypeRepository _roomTypeRepository;
        private readonly IRoomRepository _roomRepository;
        private readonly IVoucherRepository _voucherRepository;
        private readonly IPriceManagementRepository _priceManagementRepository;
        private readonly IMediaManager _mediaManager;
        private readonly IMapper _mapper;
        private readonly IValidator<RoomEditModel> _validator;
        public RoomController(IRoomTypeRepository roomTypeRepository, 
            IRoomRepository roomRepository,
            IVoucherRepository voucherRepository,
            IPriceManagementRepository priceManagementRepository,
            IMediaManager mediaManager,
            IMapper mapper,
            IValidator<RoomEditModel> validator
            )
        {           
            _roomTypeRepository = roomTypeRepository;
            _roomRepository = roomRepository;
            _voucherRepository = voucherRepository;
            _priceManagementRepository = priceManagementRepository;
            _mediaManager = mediaManager;
            _mapper = mapper;
            _validator = validator;

        }
        [HttpGet]
        public async Task<IActionResult> Index(RoomFilterModel model, [FromQuery(Name = "p")] int pageNumber = 1, [FromQuery(Name = "ps")] int pageSize = 10)
        {
            var roomQuery = _mapper.Map<RoomQuery>(model);
            var roomList = await _roomRepository.GetRoomsByQuery(roomQuery, new PagingModel() {PageSize=pageSize,PageNumber=pageNumber }, rooms => rooms.ProjectToType<RoomItem>());

            ViewBag.PageType = "Phòng";

            ViewBag.RoomList = new PaginationResult<RoomItem>(roomList);
            await PopulateRoomFilterModelAsync(model);
            ViewData["Query"] = model;
            return View("Index", model);
        }

        private async Task PopulateRoomFilterModelAsync(RoomFilterModel model)
        {
            var priceManagements = await _priceManagementRepository.GetAllAsync();
            var vouchers = await _voucherRepository.GetAllAsync();
            var roomTypes = await _roomTypeRepository.GetAllAsync();


            model.PriceManagementList = priceManagements.Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            });

            model.VoucherList = vouchers.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });
            model.RoomTypeList = roomTypes.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });
            model.StatusList= new List<SelectListItem>
            {
                //new SelectListItem { Text = "Chưa chọn", Value = null },
                new SelectListItem { Text = "Trống", Value = "false" },
                new SelectListItem { Text = "Thuê", Value = "true" }
            };
        }

        private async Task PopulateRoomEditModelAsync(RoomEditModel model)
        {
            var priceManagements = await _priceManagementRepository.GetAllAsync();
            var vouchers = await _voucherRepository.GetAllAsync();
            var roomTypes = await _roomTypeRepository.GetAllAsync();

            model.PriceManagementList = priceManagements.Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            });

            model.VoucherList = vouchers.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });
            model.RoomTypeList = roomTypes.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });
            
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id = 0)
        {
            // ID = 0 -> Thêm room mới
            // ID > 0 : Đọc dữ liệu của phòng  từ CSDL
            var room = id > 0 ? await _roomRepository.GetRoomByIdAsync(id) : null;

            // Tạo view model từ dữ liệu của phòng 
            var model = room == null ? new RoomEditModel() : _mapper.Map<RoomEditModel>(room);

            // Gán các giá trị khác nhau cho view model
            await PopulateRoomEditModelAsync(model);

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(RoomEditModel model)
        {
            

            var validationResult = await _validator.ValidateAsync(model);

            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(ModelState);
            }

            if (!ModelState.IsValid)
            {
                await PopulateRoomEditModelAsync(model);
                return View(model);
            }

            var room = model.Id > 0 ? await _roomRepository.GetRoomByIdAsync(model.Id) : null;
           
            if (room == null)
            {
                room = _mapper.Map<Room>(model);

                room.Id = 0;
                
            }
            else
            {
                string imageUrl = room.Image;
                string VideoUrl = room.Video;
                _mapper.Map(model, room);
                room.Image = imageUrl;
                room.Video = VideoUrl;
                
            }

            // Nếu người dùng có upload hình ảnh minh họa cho phòng 
            if (model.ImageFile?.Length > 0)
            {
                // Thực hiện việc lưu tập tin vào thư mực uploads
                var newImagePath = await _mediaManager.SaveFileAsync(model.ImageFile.OpenReadStream(), model.ImageFile.FileName, model.ImageFile.ContentType);

                // Nếu lưu thành công, xóa tập tin hình ảnh cũ (nếu có)
                if (!string.IsNullOrWhiteSpace(newImagePath))
                {
                    await _mediaManager.DeleteFileAsync(room.Image);
                    room.Image = newImagePath;
                }
            }
            if (model.VideoFile?.Length > 0)
            {
                // Thực hiện việc lưu tập tin vào thư mực uploads
                var newVideoPath = await _mediaManager.SaveFileAsync(model.VideoFile.OpenReadStream(), model.VideoFile.FileName, model.VideoFile.ContentType);

                // Nếu lưu thành công, xóa tập tin hình ảnh cũ (nếu có)
                if (!string.IsNullOrWhiteSpace(newVideoPath))
                {
                    await _mediaManager.DeleteFileAsync(room.Video);
                    room.Video = newVideoPath;
                }
            }
            await _roomRepository.AddOrUpdateRoom(room);

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<ActionResult> VerifyRoomSlug(int id, string urlSlug)
        {
            var slugExisted = await _roomRepository.IsRoomSlugExistedAsync(id, urlSlug);

            return slugExisted ? Json($"Slug '{urlSlug}' đã được sử dụng") : Json(true);
        }
        [HttpPost]
        public async Task<ActionResult> DeleteRoom([FromRoute]string id)
        {
            await _roomRepository.DeleteRoom(Convert.ToInt32(id));

            return RedirectToAction("Index");
        }
    }
}

RoomManagement/Areas/Admin/Controllers/RoomTypeController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Mapster;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RoomManagement.Areas.Admin.Models.RoomModel;
using RoomManagement.Areas.Admin.Models.RoomTypeModel;
using RoomManagement.Areas.Admin.Models.VoucherModel;
using RoomManagement.Core.Collections;
using RoomManagement.Core.DTO;
using RoomManagement.Core.Entites;
using RoomManagement.Models;
using RoomManagement.Services.Media;
using RoomManagement.Services.RoomMangementService.PriceManagementSerivce;
using RoomManagement.Services.RoomMangementService.RoomSerivce;
using RoomManagement.Services.RoomMangementService.RoomTypeSerivce;
using RoomManagement.Services.RoomMangementService.VoucherSerivce;

namespace RoomManagement.Areas.Admin.Controllers
{
    public class RoomTypeController : Controller
    {
        private readonly IRoomTypeRepository _roomTypeRepository;
        private readonly IRoomRepository _roomRepository;
        private readonly IVoucherRepository _voucherRepository;
        private readonly IPriceManagementRepository _priceManagementRepository;
        private readonly IMediaManager _mediaManager;
        private readonly IMapper _mapper;
        private readonly IValidator<RoomEditModel> _validator;
        public RoomTypeController(IRoomTypeRepository roomTypeRepository,
            IRoomRepository roomRepository,
            IVoucherRepository voucherRepository,
            IPriceManagementRepository priceManagementRepository,
            IMediaManager mediaManager,
            IMapper mapper,
            IValidator<RoomEditModel> validator
            )
        {
            _roomTypeRepository = roomTypeRepository;
            _roomRepository = roomRepository;
            _voucherRepository = voucherRepository;
            _priceManagementRepository = priceManagementRepository;
            _mediaManager = mediaManager;
            _mapper = mapper;
            _validator = validator;

        }

        public async Task<IActionResult> Index(

            RoomTypeFilterModel model,
            [FromQuery(Name = "p")] int pageNumber = 1,
            [FromQuery(Name = "ps")] int pageSize = 10
            )
        {
            var roomTypeQuery = _mapper.Map<RoomTypeQuery>(model);
            var roomTypeList = await _roomTypeRepository.GetRoomTypesByQuery(roomTypeQuery, new PagingModel() { PageSize = pageSize, PageNumber = pageNumber }, roomTypes => roomTypes.ProjectToType<RoomTypeDto>());

            ViewBag.PageType = "Loại phòng";

            ViewBag.RoomTypeList = new PaginationResult<RoomTypeDto>(roomTypeList);
            ViewData["Query"] = model;
            return View("Index", model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromServices]
             IValidator<RoomTypeEditModel> validator, RoomTypeEditModel model)
        {

            //slug null
            var validationResult = await validator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(ModelState);
            }
            if (!ModelState.IsValid)
            {
                //await PopulatePostsEditModelAsync(model);
                return View(model);
            }

            var roomType = model.Id > 0
              ? await _roomTypeRepository.GetRoomTypeByIdAsync(model.Id)
              : null;

            if (roomType == null)
            {
                roomType = _mapper.Map<RoomType>(model);
                roomType.Id = 0;

            }
            else
            {
                _mapper.Map(model, roomType);

            }
            await _roomTypeRepository.AddOrUpdateRoomType(roomType);
            return RedirectToAction(nameof(Index));

        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var roomType = id > 0
           ? await _roomTypeRepository.GetRoomTypeByIdAsync(id)
           : null;

            var model = roomType == null
            ? new RoomTypeEditModel()
            : _mapper.Map<RoomTypeEditModel>(roomType);

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> DeleteRoomType(int id)
        {
            var roomTypeQuery = await _roomTypeRepository.DeleteRoomType(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> VerifyRoomTypeSlug(int id, string urlSlug)
        {
            var slugExisted = await _roomTypeRepository.IsRoomTypeSlugExistedAsync(id, urlSlug);
            return slugExisted ? Json($"slug '{urlSlug}'  đã được sử dụng") : Json(true);
        }

        public async Task PopulateRoomTypesFitlterModelAsync(RoomTypeFilterModel model)
        {
            var roomTypes = await _roomTypeRepository.GetAllAsync();
            model.RoomTypeList = roomTypes.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = c.Id.ToString(),
            });
        }
    }
}

RoomManagement/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Nhóm 5 - Hệ thống quản lý phòng</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="~/asset/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/asset/css/sb-admin-2.css" rel="stylesheet" />
    <link href="~/asset/css/sb-admin-2.min.css" rel="stylesheet" />
    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">
    @await RenderSectionAsync("styles",false)
</head>
<body id="page-top">

    <div id="wrapper">
        <partial name="_Wrapper" />
        @RenderBody()
    </div>



    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn có chắc muốn thoát?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Đóng">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Chọn mục "Đăng xuất" ở bên dưới nếu bạn đã sẵn sàng để đăng xuất.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                    <a class="btn btn-primary" href="#">Đăng suất</a>
                </div>
            </div>
        </div>
    </div>







    <script src="~/asset/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/asset/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/asset/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/asset/js/sb-admin-2.min.js"></script>
    <script src="~/asset/vendor/chart.js/chart.min.js"></script>
    <script src="~/asset/js/demo/chart-area-demo.js"></script>
    <script src="~/asset/js/demo/chart-pie-demo.js"></script>
    @await RenderSectionAsync("scripts",false)
</body>

</html>

RoomManagement/Areas/Admin/Views/Shared/_Pagination.cshtml
@model PagingMetadata

@{
    var query = ViewData["Query"] as IPageQuery;
}

<div class="row">
    <div class="col-sm-12 col-md-5">
        <div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">
            @*Tổng @Model.TotalItemCount*@
            @if (ViewBag.PageType != null)
            {
                <text>Tổng @Model.TotalItemCount @ViewBag.PageType</text>
            }
        </div>
    </div>
    <div class="col-sm-12 col-md-7">
        <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    @if (Model.IsFirstPage)
                    {
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trở lại</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" href="room?p=@(Model.PageNumber - 1)&ps=@Model.PageSize&@query.CreateQuery()">Trở lại</a>
                        </li>
                    }

                    @for (int i = 1; i <= Model.PageCount; i++)
                    {
                        <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                            <a class="page-link" href="room?p=@i&ps=@Model.PageSize&@query.CreateQuery()">@i</a>
                        </li>
                    }

                    @if (Model.IsLastPage)
                    {
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Tiếp theo</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" href="room?p=@(Model.PageNumber + 1)&ps=@Model.PageSize&@query.CreateQuery()">Tiếp theo</a>
                        </li>
                    }
                </ul>
            </nav>
        </div>
    </div>
</div>

RoomManagement/Areas/Admin/Views/Shared/_Wrapper.cshtml
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Nhóm <sup>5</sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Trang chủ</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Loại phòng
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="" data-toggle="collapse" data-target="#collapseRoomType"
               aria-expanded="true" aria-controls="collapseRoomType">
                <i class="fas fa-fw fa-cog"></i>
                <span>Quản lý loại phòng</span>
            </a>
            <div id="collapseRoomType" class="collapse" aria-labelledby="headingTwo"
                 data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Các chức năng:</h6>
                    <a class="collapse-item" asp-area="Admin" asp-controller="RoomType" asp-action="Index">Xem loại phòng</a>
                    <a class="collapse-item" asp-controller="RoomType" asp-area="Admin" asp-action="Edit">Thêm loại phòng</a>
                </div>
            </div>
        </li>
        <!-- Heading -->
        <div class="sidebar-heading">
            Phòng
        </div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseRoom"
               aria-expanded="true" aria-controls="collapseRoom">
                <i class="fas fa-fw fa-cog"></i>
                <span>Quản lý phòng</span>
            </a>
            <div id="collapseRoom" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Các chức năng:</h6>
                    <a class="collapse-item" asp-area="Admin" asp-controller="Room" asp-action="Index">Xem phòng</a>
                    <a class="collapse-item" asp-controller="Room" asp-area="Admin" asp-action="Edit">Thêm phòng</a>
                </div>
            </div>
        </li>
        <!-- Heading -->
        <div class="sidebar-heading">
            Voucher
        </div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVoucher"
               aria-expanded="true" aria-controls="collapseVoucher">
                <i class="fas fa-fw fa-cog"></i>
                <span>Quản lý Voucher</span>
            </a>
            <div id="collapseVoucher" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Các chức năng:</h6>
                    <a class="collapse-item" asp-area="Admin" asp-controller="Voucher" asp-action="Index">Xem Voucher</a>
                    <a class="collapse-item" asp-controller="Voucher" asp-area="Admin" asp-action="Edit">Thêm Voucher</a>
                </div>
            </div>
        </li>
        <!-- Heading -->
        <div class="sidebar-heading">
            Giá phòng
        </div>
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePrice"
               aria-expanded="true" aria-controls="collapsePrice">
                <i class="fas fa-fw fa-cog"></i>
                <span>Quản lý giá phòng</span>
            </a>
            <div id="collapsePrice" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Các chức năng:</h6>
                    <a class="collapse-item" asp-area="Admin" asp-controller="PriceManagement" asp-action="Index">Xem giá phòng</a>
                    <a class="collapse-item" asp-controller="PriceManagement" asp-area="Admin" asp-action="Edit">Thêm giá phòng</a>
                </div>
            </div>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">



        <!-- Nav Item - Tables -->
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <!-- End of Content Wrapper -->

</div>